name: citra-build

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  macos:
    runs-on: 'macos-26'
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      CACHE_ENABLED: ${{ github.ref_type != 'tag' }}
      OS: macos
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up cache
        if: ${{ env.CACHE_ENABLED == 'true' }}
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install tools
        run: brew install ccache ninja spirv-tools
      - name: Build (arm64)
        run: BUILD_ARCH=arm64 ./.ci/macos.sh
      - name: Build (x86_64)
        run: BUILD_ARCH=x86_64 ./.ci/macos.sh
      - name: Create universal app
        run: ./.ci/macos-universal.sh
      - name: Prepare for packing
        run: |
          mkdir build/bundle
          cp -r build/x86_64/bundle build/bundle/x86_64
          cp -r build/arm64/bundle build/bundle/arm64
          cp -r build/universal/bundle build/bundle/universal
      - name: Pack
        env:
          PACK_INDIVIDUALLY: 1
        run: ./.ci/pack.sh
      - name: Generate SBOM
        if: ${{ github.ref_type == 'tag' }}
        uses: anchore/sbom-action@v0
        with:
          path: build/
          format: spdx-json
          output-file: artifacts/macos.spdx.json
          upload-artifact: false
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OS }}
          path: artifacts/
      - name: Attest artifacts
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/attest@v4
        with:
          subject-path: |
            artifacts/*.zip
          sbom-path: artifacts/macos.spdx.json
